
SHELL=/bin/bash

an2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x05.ap
	echo "# Remake an2v0x05.cif"
an2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x1.ap
	echo "# Remake an2v0x1.cif"
an2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x2.ap
	echo "# Remake an2v0x2.cif"
an2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x3.ap
	echo "# Remake an2v0x3.cif"
an2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x4.ap
	echo "# Remake an2v0x4.cif"
an2v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x6.ap
	echo "# Remake an2v0x6.cif"
an2v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v0x8.ap
	echo "# Remake an2v0x8.cif"
an2v2x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v2x2.ap
	echo "# Remake an2v2x2.cif"
an2v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v4x1.ap
	echo "# Remake an2v4x1.cif"
an2v4x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v4x2.ap
	echo "# Remake an2v4x2.cif"
an2v4x4.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v4x4.ap
	echo "# Remake an2v4x4.cif"
an2v4x8.cif: /usr/share/pharosc/alliance/cells/vsclib/an2v4x8.ap
	echo "# Remake an2v4x8.cif"
an3v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v0x05.ap
	echo "# Remake an3v0x05.cif"
an3v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v0x1.ap
	echo "# Remake an3v0x1.cif"
an3v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v0x2.ap
	echo "# Remake an3v0x2.cif"
an3v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v0x4.ap
	echo "# Remake an3v0x4.cif"
an3v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v4x1.ap
	echo "# Remake an3v4x1.cif"
an3v4x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v4x2.ap
	echo "# Remake an3v4x2.cif"
an3v6x05.cif: /usr/share/pharosc/alliance/cells/vsclib/an3v6x05.ap
	echo "# Remake an3v6x05.cif"
an4v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/an4v0x05.ap
	echo "# Remake an4v0x05.cif"
an4v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an4v0x1.ap
	echo "# Remake an4v0x1.cif"
an4v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/an4v0x2.ap
	echo "# Remake an4v0x2.cif"
an4v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/an4v0x4.ap
	echo "# Remake an4v0x4.cif"
an4v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/an4v4x1.ap
	echo "# Remake an4v4x1.cif"
aoi112v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi112v0x05.ap
	echo "# Remake aoi112v0x05.cif"
aoi211v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x05.ap
	echo "# Remake aoi211v0x05.cif"
aoi211v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x1.ap
	echo "# Remake aoi211v0x1.cif"
aoi211v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x2.ap
	echo "# Remake aoi211v0x2.cif"
aoi211v5x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi211v5x05.ap
	echo "# Remake aoi211v5x05.cif"
aoi21a2bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2bv0x05.ap
	echo "# Remake aoi21a2bv0x05.cif"
aoi21a2bv5x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2bv5x05.ap
	echo "# Remake aoi21a2bv5x05.cif"
aoi21a2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2v0x05.ap
	echo "# Remake aoi21a2v0x05.cif"
aoi21bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21bv0x05.ap
	echo "# Remake aoi21bv0x05.cif"
aoi21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x05.ap
	echo "# Remake aoi21v0x05.cif"
aoi21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x1.ap
	echo "# Remake aoi21v0x1.cif"
aoi21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x2.ap
	echo "# Remake aoi21v0x2.cif"
aoi22v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x05.ap
	echo "# Remake aoi22v0x05.cif"
aoi22v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x1.ap
	echo "# Remake aoi22v0x1.cif"
aoi22v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x2.ap
	echo "# Remake aoi22v0x2.cif"
aoi22v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x3.ap
	echo "# Remake aoi22v0x3.cif"
aoi22v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x4.ap
	echo "# Remake aoi22v0x4.cif"
aoi22v5x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi22v5x05.ap
	echo "# Remake aoi22v5x05.cif"
aoi31v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x05.ap
	echo "# Remake aoi31v0x05.cif"
aoi31v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x1.ap
	echo "# Remake aoi31v0x1.cif"
aoi31v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x2.ap
	echo "# Remake aoi31v0x2.cif"
aoi31v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x3.ap
	echo "# Remake aoi31v0x3.cif"
aon21bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x05.ap
	echo "# Remake aon21bv0x05.cif"
aon21bv0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x1.ap
	echo "# Remake aon21bv0x1.cif"
aon21bv0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x2.ap
	echo "# Remake aon21bv0x2.cif"
aon21bv0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x3.ap
	echo "# Remake aon21bv0x3.cif"
aon21bv0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x4.ap
	echo "# Remake aon21bv0x4.cif"
aon21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/aon21v0x05.ap
	echo "# Remake aon21v0x05.cif"
bf1v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x05.ap
	echo "# Remake bf1v0x05.cif"
bf1v0x12.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x12.ap
	echo "# Remake bf1v0x12.cif"
bf1v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x1.ap
	echo "# Remake bf1v0x1.cif"
bf1v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x2.ap
	echo "# Remake bf1v0x2.cif"
bf1v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x3.ap
	echo "# Remake bf1v0x3.cif"
bf1v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x4.ap
	echo "# Remake bf1v0x4.cif"
bf1v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x6.ap
	echo "# Remake bf1v0x6.cif"
bf1v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x8.ap
	echo "# Remake bf1v0x8.cif"
bf1v1x2.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v1x2.ap
	echo "# Remake bf1v1x2.cif"
bf1v2x1.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x1.ap
	echo "# Remake bf1v2x1.cif"
bf1v2x2.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x2.ap
	echo "# Remake bf1v2x2.cif"
bf1v2x3.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x3.ap
	echo "# Remake bf1v2x3.cif"
bf1v2x4.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x4.ap
	echo "# Remake bf1v2x4.cif"
bf1v2x6.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x6.ap
	echo "# Remake bf1v2x6.cif"
bf1v2x8.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x8.ap
	echo "# Remake bf1v2x8.cif"
bf1v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v4x1.ap
	echo "# Remake bf1v4x1.cif"
bf1v5x05.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x05.ap
	echo "# Remake bf1v5x05.cif"
bf1v5x1.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x1.ap
	echo "# Remake bf1v5x1.cif"
bf1v5x2.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x2.ap
	echo "# Remake bf1v5x2.cif"
bf1v5x4.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x4.ap
	echo "# Remake bf1v5x4.cif"
bf1v6x2.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v6x2.ap
	echo "# Remake bf1v6x2.cif"
bf1v8x4.cif: /usr/share/pharosc/alliance/cells/vsclib/bf1v8x4.ap
	echo "# Remake bf1v8x4.cif"
bsi2v2x1.cif: /usr/share/pharosc/alliance/cells/vsclib/bsi2v2x1.ap
	echo "# Remake bsi2v2x1.cif"
cgi2abv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x05.ap
	echo "# Remake cgi2abv0x05.cif"
cgi2abv0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x1.ap
	echo "# Remake cgi2abv0x1.cif"
cgi2abv0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x2.ap
	echo "# Remake cgi2abv0x2.cif"
cgi2bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x05.ap
	echo "# Remake cgi2bv0x05.cif"
cgi2bv0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x1.ap
	echo "# Remake cgi2bv0x1.cif"
cgi2bv0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x2.ap
	echo "# Remake cgi2bv0x2.cif"
cgi2bv0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x3.ap
	echo "# Remake cgi2bv0x3.cif"
cgi2cv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x05.ap
	echo "# Remake cgi2cv0x05.cif"
cgi2cv0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x1.ap
	echo "# Remake cgi2cv0x1.cif"
cgi2cv0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x2.ap
	echo "# Remake cgi2cv0x2.cif"
cgi2cv0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x3.ap
	echo "# Remake cgi2cv0x3.cif"
cgi2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x05.ap
	echo "# Remake cgi2v0x05.cif"
cgi2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x1.ap
	echo "# Remake cgi2v0x1.cif"
cgi2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x2.ap
	echo "# Remake cgi2v0x2.cif"
cgi2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x3.ap
	echo "# Remake cgi2v0x3.cif"
dfnt1v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/dfnt1v0x2.ap
	echo "# Remake dfnt1v0x2.cif"
dly1v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/dly1v0x05.ap
	echo "# Remake dly1v0x05.cif"
dly2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/dly2v0x05.ap
	echo "# Remake dly2v0x05.cif"
dly2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/dly2v0x1.ap
	echo "# Remake dly2v0x1.cif"
ha2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/ha2v0x2.ap
	echo "# Remake ha2v0x2.cif"
iv1v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x05.ap
	echo "# Remake iv1v0x05.cif"
iv1v0x12.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x12.ap
	echo "# Remake iv1v0x12.cif"
iv1v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x1.ap
	echo "# Remake iv1v0x1.cif"
iv1v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x2.ap
	echo "# Remake iv1v0x2.cif"
iv1v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x3.ap
	echo "# Remake iv1v0x3.cif"
iv1v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x4.ap
	echo "# Remake iv1v0x4.cif"
iv1v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x6.ap
	echo "# Remake iv1v0x6.cif"
iv1v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x8.ap
	echo "# Remake iv1v0x8.cif"
iv1v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x05.ap
	echo "# Remake iv1v1x05.cif"
iv1v1x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x1.ap
	echo "# Remake iv1v1x1.cif"
iv1v1x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x2.ap
	echo "# Remake iv1v1x2.cif"
iv1v1x4.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x4.ap
	echo "# Remake iv1v1x4.cif"
iv1v1x8.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x8.ap
	echo "# Remake iv1v1x8.cif"
iv1v2x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v2x2.ap
	echo "# Remake iv1v2x2.cif"
iv1v3x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x1.ap
	echo "# Remake iv1v3x1.cif"
iv1v3x3.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x3.ap
	echo "# Remake iv1v3x3.cif"
iv1v3x6.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x6.ap
	echo "# Remake iv1v3x6.cif"
iv1v4x12.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x12.ap
	echo "# Remake iv1v4x12.cif"
iv1v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x1.ap
	echo "# Remake iv1v4x1.cif"
iv1v4x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x2.ap
	echo "# Remake iv1v4x2.cif"
iv1v4x3.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x3.ap
	echo "# Remake iv1v4x3.cif"
iv1v4x4.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x4.ap
	echo "# Remake iv1v4x4.cif"
iv1v4x6.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x6.ap
	echo "# Remake iv1v4x6.cif"
iv1v4x8.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x8.ap
	echo "# Remake iv1v4x8.cif"
iv1v5x12.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x12.ap
	echo "# Remake iv1v5x12.cif"
iv1v5x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x1.ap
	echo "# Remake iv1v5x1.cif"
iv1v5x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x2.ap
	echo "# Remake iv1v5x2.cif"
iv1v5x3.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x3.ap
	echo "# Remake iv1v5x3.cif"
iv1v5x4.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x4.ap
	echo "# Remake iv1v5x4.cif"
iv1v5x6.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x6.ap
	echo "# Remake iv1v5x6.cif"
iv1v5x8.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x8.ap
	echo "# Remake iv1v5x8.cif"
iv1v6x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v6x1.ap
	echo "# Remake iv1v6x1.cif"
iv1v6x2.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v6x2.ap
	echo "# Remake iv1v6x2.cif"
iv1v7x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v7x1.ap
	echo "# Remake iv1v7x1.cif"
iv1v8x1.cif: /usr/share/pharosc/alliance/cells/vsclib/iv1v8x1.ap
	echo "# Remake iv1v8x1.cif"
mxi2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x05.ap
	echo "# Remake mxi2v0x05.cif"
mxi2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x1.ap
	echo "# Remake mxi2v0x1.cif"
mxi2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x2.ap
	echo "# Remake mxi2v0x2.cif"
mxi2v2x05.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x05.ap
	echo "# Remake mxi2v2x05.cif"
mxi2v2x1.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x1.ap
	echo "# Remake mxi2v2x1.cif"
mxi2v2x2.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x2.ap
	echo "# Remake mxi2v2x2.cif"
mxi2v2x3.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x3.ap
	echo "# Remake mxi2v2x3.cif"
mxi2v2x4.cif: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x4.ap
	echo "# Remake mxi2v2x4.cif"
mxn2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/mxn2v0x05.ap
	echo "# Remake mxn2v0x05.cif"
mxn2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/mxn2v0x1.ap
	echo "# Remake mxn2v0x1.cif"
mxn2v2x1.cif: /usr/share/pharosc/alliance/cells/vsclib/mxn2v2x1.ap
	echo "# Remake mxn2v2x1.cif"
nd2abv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x05.ap
	echo "# Remake nd2abv0x05.cif"
nd2abv0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x1.ap
	echo "# Remake nd2abv0x1.cif"
nd2abv0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x2.ap
	echo "# Remake nd2abv0x2.cif"
nd2abv0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x3.ap
	echo "# Remake nd2abv0x3.cif"
nd2abv0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x4.ap
	echo "# Remake nd2abv0x4.cif"
nd2av0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x05.ap
	echo "# Remake nd2av0x05.cif"
nd2av0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x1.ap
	echo "# Remake nd2av0x1.cif"
nd2av0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x2.ap
	echo "# Remake nd2av0x2.cif"
nd2av0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x3.ap
	echo "# Remake nd2av0x3.cif"
nd2av0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x4.ap
	echo "# Remake nd2av0x4.cif"
nd2av0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x6.ap
	echo "# Remake nd2av0x6.cif"
nd2av0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x8.ap
	echo "# Remake nd2av0x8.cif"
nd2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x05.ap
	echo "# Remake nd2v0x05.cif"
nd2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x1.ap
	echo "# Remake nd2v0x1.cif"
nd2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x2.ap
	echo "# Remake nd2v0x2.cif"
nd2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x3.ap
	echo "# Remake nd2v0x3.cif"
nd2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x4.ap
	echo "# Remake nd2v0x4.cif"
nd2v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x6.ap
	echo "# Remake nd2v0x6.cif"
nd2v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x8.ap
	echo "# Remake nd2v0x8.cif"
nd2v3x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x05.ap
	echo "# Remake nd2v3x05.cif"
nd2v3x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x1.ap
	echo "# Remake nd2v3x1.cif"
nd2v3x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x2.ap
	echo "# Remake nd2v3x2.cif"
nd2v3x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x3.ap
	echo "# Remake nd2v3x3.cif"
nd2v3x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x4.ap
	echo "# Remake nd2v3x4.cif"
nd2v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x1.ap
	echo "# Remake nd2v4x1.cif"
nd2v4x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x2.ap
	echo "# Remake nd2v4x2.cif"
nd2v4x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x3.ap
	echo "# Remake nd2v4x3.cif"
nd2v4x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x4.ap
	echo "# Remake nd2v4x4.cif"
nd2v4x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x6.ap
	echo "# Remake nd2v4x6.cif"
nd2v4x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x8.ap
	echo "# Remake nd2v4x8.cif"
nd2v5x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x05.ap
	echo "# Remake nd2v5x05.cif"
nd2v5x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x1.ap
	echo "# Remake nd2v5x1.cif"
nd2v5x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x2.ap
	echo "# Remake nd2v5x2.cif"
nd2v5x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x3.ap
	echo "# Remake nd2v5x3.cif"
nd2v5x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x4.ap
	echo "# Remake nd2v5x4.cif"
nd2v5x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x6.ap
	echo "# Remake nd2v5x6.cif"
nd2v5x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x8.ap
	echo "# Remake nd2v5x8.cif"
nd2v6x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd2v6x3.ap
	echo "# Remake nd2v6x3.cif"
nd3abv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3abv0x05.ap
	echo "# Remake nd3abv0x05.cif"
nd3av0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3av0x05.ap
	echo "# Remake nd3av0x05.cif"
nd3v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x05.ap
	echo "# Remake nd3v0x05.cif"
nd3v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x1.ap
	echo "# Remake nd3v0x1.cif"
nd3v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x2.ap
	echo "# Remake nd3v0x2.cif"
nd3v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x3.ap
	echo "# Remake nd3v0x3.cif"
nd3v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x4.ap
	echo "# Remake nd3v0x4.cif"
nd3v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x6.ap
	echo "# Remake nd3v0x6.cif"
nd3v5x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x2.ap
	echo "# Remake nd3v5x2.cif"
nd3v5x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x3.ap
	echo "# Remake nd3v5x3.cif"
nd3v5x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x4.ap
	echo "# Remake nd3v5x4.cif"
nd3v5x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x6.ap
	echo "# Remake nd3v5x6.cif"
nd3v6x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nd3v6x6.ap
	echo "# Remake nd3v6x6.cif"
nd4v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x05.ap
	echo "# Remake nd4v0x05.cif"
nd4v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x1.ap
	echo "# Remake nd4v0x1.cif"
nd4v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x2.ap
	echo "# Remake nd4v0x2.cif"
nd4v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x3.ap
	echo "# Remake nd4v0x3.cif"
nr2av0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x1.ap
	echo "# Remake nr2av0x1.cif"
nr2av0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x2.ap
	echo "# Remake nr2av0x2.cif"
nr2av0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x3.ap
	echo "# Remake nr2av0x3.cif"
nr2av0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x4.ap
	echo "# Remake nr2av0x4.cif"
nr2av0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x6.ap
	echo "# Remake nr2av0x6.cif"
nr2av1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2av1x05.ap
	echo "# Remake nr2av1x05.cif"
nr2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x05.ap
	echo "# Remake nr2v0x05.cif"
nr2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x1.ap
	echo "# Remake nr2v0x1.cif"
nr2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x2.ap
	echo "# Remake nr2v0x2.cif"
nr2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x3.ap
	echo "# Remake nr2v0x3.cif"
nr2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x4.ap
	echo "# Remake nr2v0x4.cif"
nr2v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x6.ap
	echo "# Remake nr2v0x6.cif"
nr2v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x8.ap
	echo "# Remake nr2v0x8.cif"
nr2v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x05.ap
	echo "# Remake nr2v1x05.cif"
nr2v1x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x1.ap
	echo "# Remake nr2v1x1.cif"
nr2v1x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x2.ap
	echo "# Remake nr2v1x2.cif"
nr2v1x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x3.ap
	echo "# Remake nr2v1x3.cif"
nr2v1x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x4.ap
	echo "# Remake nr2v1x4.cif"
nr2v1x6.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x6.ap
	echo "# Remake nr2v1x6.cif"
nr2v1x8.cif: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x8.ap
	echo "# Remake nr2v1x8.cif"
nr3abv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3abv0x05.ap
	echo "# Remake nr3abv0x05.cif"
nr3av0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3av0x05.ap
	echo "# Remake nr3av0x05.cif"
nr3v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x05.ap
	echo "# Remake nr3v0x05.cif"
nr3v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x1.ap
	echo "# Remake nr3v0x1.cif"
nr3v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x2.ap
	echo "# Remake nr3v0x2.cif"
nr3v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x3.ap
	echo "# Remake nr3v0x3.cif"
nr3v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x4.ap
	echo "# Remake nr3v0x4.cif"
nr3v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr3v1x05.ap
	echo "# Remake nr3v1x05.cif"
nr4v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/nr4v0x1.ap
	echo "# Remake nr4v0x1.cif"
nr4v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/nr4v0x2.ap
	echo "# Remake nr4v0x2.cif"
nr4v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/nr4v1x05.ap
	echo "# Remake nr4v1x05.cif"
oai211v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai211v0x05.ap
	echo "# Remake oai211v0x05.cif"
oai211v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/oai211v0x1.ap
	echo "# Remake oai211v0x1.cif"
oai21a2bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21a2bv0x05.ap
	echo "# Remake oai21a2bv0x05.cif"
oai21a2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21a2v0x05.ap
	echo "# Remake oai21a2v0x05.cif"
oai21a2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21a2v0x1.ap
	echo "# Remake oai21a2v0x1.cif"
oai21bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21bv0x05.ap
	echo "# Remake oai21bv0x05.cif"
oai21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x05.ap
	echo "# Remake oai21v0x05.cif"
oai21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x1.ap
	echo "# Remake oai21v0x1.cif"
oai21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x2.ap
	echo "# Remake oai21v0x2.cif"
oai21v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x3.ap
	echo "# Remake oai21v0x3.cif"
oai21v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x4.ap
	echo "# Remake oai21v0x4.cif"
oai21v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x6.ap
	echo "# Remake oai21v0x6.cif"
oai21v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x8.ap
	echo "# Remake oai21v0x8.cif"
oai22v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x05.ap
	echo "# Remake oai22v0x05.cif"
oai22v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x1.ap
	echo "# Remake oai22v0x1.cif"
oai22v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x2.ap
	echo "# Remake oai22v0x2.cif"
oai23av0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai23av0x05.ap
	echo "# Remake oai23av0x05.cif"
oai31v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x05.ap
	echo "# Remake oai31v0x05.cif"
oai31v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x1.ap
	echo "# Remake oai31v0x1.cif"
oai31v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x2.ap
	echo "# Remake oai31v0x2.cif"
oan21bv0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oan21bv0x05.ap
	echo "# Remake oan21bv0x05.cif"
oan21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/oan21v0x05.ap
	echo "# Remake oan21v0x05.cif"
or2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x05.ap
	echo "# Remake or2v0x05.cif"
or2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x1.ap
	echo "# Remake or2v0x1.cif"
or2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x2.ap
	echo "# Remake or2v0x2.cif"
or2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x3.ap
	echo "# Remake or2v0x3.cif"
or2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x4.ap
	echo "# Remake or2v0x4.cif"
or2v0x8.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v0x8.ap
	echo "# Remake or2v0x8.cif"
or2v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v4x1.ap
	echo "# Remake or2v4x1.cif"
or2v7x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or2v7x2.ap
	echo "# Remake or2v7x2.cif"
or3v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v0x05.ap
	echo "# Remake or3v0x05.cif"
or3v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v0x1.ap
	echo "# Remake or3v0x1.cif"
or3v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v0x2.ap
	echo "# Remake or3v0x2.cif"
or3v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v0x3.ap
	echo "# Remake or3v0x3.cif"
or3v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v0x4.ap
	echo "# Remake or3v0x4.cif"
or3v3x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v3x2.ap
	echo "# Remake or3v3x2.cif"
or3v4x05.cif: /usr/share/pharosc/alliance/cells/vsclib/or3v4x05.ap
	echo "# Remake or3v4x05.cif"
or4v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v0x05.ap
	echo "# Remake or4v0x05.cif"
or4v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v0x1.ap
	echo "# Remake or4v0x1.cif"
or4v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v0x2.ap
	echo "# Remake or4v0x2.cif"
or4v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v0x3.ap
	echo "# Remake or4v0x3.cif"
or4v3x2.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v3x2.ap
	echo "# Remake or4v3x2.cif"
or4v4x05.cif: /usr/share/pharosc/alliance/cells/vsclib/or4v4x05.ap
	echo "# Remake or4v4x05.cif"
rowend_x0.cif: /usr/share/pharosc/alliance/cells/vsclib/rowend_x0.ap
	echo "# Remake rowend_x0.cif"
tie_x0.cif: /usr/share/pharosc/alliance/cells/vsclib/tie_x0.ap
	echo "# Remake tie_x0.cif"
vddtie.cif: /usr/share/pharosc/alliance/cells/vsclib/vddtie.ap
	echo "# Remake vddtie.cif"
vfeed1.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed1.ap
	echo "# Remake vfeed1.cif"
vfeed2.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed2.ap
	echo "# Remake vfeed2.cif"
vfeed3.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed3.ap
	echo "# Remake vfeed3.cif"
vfeed4.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed4.ap
	echo "# Remake vfeed4.cif"
vfeed5.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed5.ap
	echo "# Remake vfeed5.cif"
vfeed6.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed6.ap
	echo "# Remake vfeed6.cif"
vfeed7.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed7.ap
	echo "# Remake vfeed7.cif"
vfeed8.cif: /usr/share/pharosc/alliance/cells/vsclib/vfeed8.ap
	echo "# Remake vfeed8.cif"
vsstie.cif: /usr/share/pharosc/alliance/cells/vsclib/vsstie.ap
	echo "# Remake vsstie.cif"
xaoi21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x05.ap
	echo "# Remake xaoi21v0x05.cif"
xaoi21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x1.ap
	echo "# Remake xaoi21v0x1.cif"
xaoi21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x2.ap
	echo "# Remake xaoi21v0x2.cif"
xaon21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x05.ap
	echo "# Remake xaon21v0x05.cif"
xaon21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x1.ap
	echo "# Remake xaon21v0x1.cif"
xaon21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x2.ap
	echo "# Remake xaon21v0x2.cif"
xaon21v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x3.ap
	echo "# Remake xaon21v0x3.cif"
xnai21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnai21v0x05.ap
	echo "# Remake xnai21v0x05.cif"
xnai21v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnai21v1x05.ap
	echo "# Remake xnai21v1x05.cif"
xnai21v2x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnai21v2x05.ap
	echo "# Remake xnai21v2x05.cif"
xnr2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x05.ap
	echo "# Remake xnr2v0x05.cif"
xnr2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x1.ap
	echo "# Remake xnr2v0x1.cif"
xnr2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x2.ap
	echo "# Remake xnr2v0x2.cif"
xnr2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x3.ap
	echo "# Remake xnr2v0x3.cif"
xnr2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x4.ap
	echo "# Remake xnr2v0x4.cif"
xnr2v6x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v6x1.ap
	echo "# Remake xnr2v6x1.cif"
xnr2v8x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr2v8x05.ap
	echo "# Remake xnr2v8x05.cif"
xnr3v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x05.ap
	echo "# Remake xnr3v1x05.cif"
xnr3v1x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x1.ap
	echo "# Remake xnr3v1x1.cif"
xnr3v1x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x2.ap
	echo "# Remake xnr3v1x2.cif"
xooi21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x05.ap
	echo "# Remake xooi21v0x05.cif"
xooi21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x1.ap
	echo "# Remake xooi21v0x1.cif"
xooi21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x2.ap
	echo "# Remake xooi21v0x2.cif"
xoon21v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x05.ap
	echo "# Remake xoon21v0x05.cif"
xoon21v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x1.ap
	echo "# Remake xoon21v0x1.cif"
xoon21v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x2.ap
	echo "# Remake xoon21v0x2.cif"
xoon21v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x3.ap
	echo "# Remake xoon21v0x3.cif"
xor2v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x05.ap
	echo "# Remake xor2v0x05.cif"
xor2v0x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x1.ap
	echo "# Remake xor2v0x1.cif"
xor2v0x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x2.ap
	echo "# Remake xor2v0x2.cif"
xor2v0x3.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x3.ap
	echo "# Remake xor2v0x3.cif"
xor2v0x4.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x4.ap
	echo "# Remake xor2v0x4.cif"
xor2v0x6.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x6.ap
	echo "# Remake xor2v0x6.cif"
xor2v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v1x05.ap
	echo "# Remake xor2v1x05.cif"
xor2v1x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v1x1.ap
	echo "# Remake xor2v1x1.cif"
xor2v2x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x05.ap
	echo "# Remake xor2v2x05.cif"
xor2v2x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x1.ap
	echo "# Remake xor2v2x1.cif"
xor2v2x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x2.ap
	echo "# Remake xor2v2x2.cif"
xor2v3x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v3x1.ap
	echo "# Remake xor2v3x1.cif"
xor2v4x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v4x1.ap
	echo "# Remake xor2v4x1.cif"
xor2v5x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v5x1.ap
	echo "# Remake xor2v5x1.cif"
xor2v6x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v6x1.ap
	echo "# Remake xor2v6x1.cif"
xor2v7x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v7x1.ap
	echo "# Remake xor2v7x1.cif"
xor2v8x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x05.ap
	echo "# Remake xor2v8x05.cif"
xor2v8x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x1.ap
	echo "# Remake xor2v8x1.cif"
xor2v8x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x2.ap
	echo "# Remake xor2v8x2.cif"
xor3v0x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor3v0x05.ap
	echo "# Remake xor3v0x05.cif"
xor3v1x05.cif: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x05.ap
	echo "# Remake xor3v1x05.cif"
xor3v1x1.cif: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x1.ap
	echo "# Remake xor3v1x1.cif"
xor3v1x2.cif: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x2.ap
	echo "# Remake xor3v1x2.cif"
