
SHELL=/bin/bash

a2_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/a2_x2.ap
	echo "# Remake a2_x2.gds"
a2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/a2_x4.ap
	echo "# Remake a2_x4.gds"
a3_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/a3_x2.ap
	echo "# Remake a3_x2.gds"
a3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/a3_x4.ap
	echo "# Remake a3_x4.gds"
a4_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/a4_x2.ap
	echo "# Remake a4_x2.gds"
a4_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/a4_x4.ap
	echo "# Remake a4_x4.gds"
an12_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/an12_x1.ap
	echo "# Remake an12_x1.gds"
an12_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/an12_x4.ap
	echo "# Remake an12_x4.gds"
ao22_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/ao22_x2.ap
	echo "# Remake ao22_x2.gds"
ao22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/ao22_x4.ap
	echo "# Remake ao22_x4.gds"
ao2o22_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/ao2o22_x2.ap
	echo "# Remake ao2o22_x2.gds"
ao2o22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/ao2o22_x4.ap
	echo "# Remake ao2o22_x4.gds"
buf_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/buf_x2.ap
	echo "# Remake buf_x2.gds"
buf_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/buf_x4.ap
	echo "# Remake buf_x4.gds"
buf_x8.gds: /usr/share/pharosc/alliance/cells/ssxlib/buf_x8.ap
	echo "# Remake buf_x8.gds"
fulladder_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/fulladder_x2.ap
	echo "# Remake fulladder_x2.gds"
fulladder_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/fulladder_x4.ap
	echo "# Remake fulladder_x4.gds"
halfadder_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/halfadder_x2.ap
	echo "# Remake halfadder_x2.gds"
halfadder_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/halfadder_x4.ap
	echo "# Remake halfadder_x4.gds"
inv_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/inv_x1.ap
	echo "# Remake inv_x1.gds"
inv_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/inv_x2.ap
	echo "# Remake inv_x2.gds"
inv_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/inv_x4.ap
	echo "# Remake inv_x4.gds"
inv_x8.gds: /usr/share/pharosc/alliance/cells/ssxlib/inv_x8.ap
	echo "# Remake inv_x8.gds"
mx2_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/mx2_x2.ap
	echo "# Remake mx2_x2.gds"
mx2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/mx2_x4.ap
	echo "# Remake mx2_x4.gds"
mx3_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/mx3_x2.ap
	echo "# Remake mx3_x2.gds"
mx3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/mx3_x4.ap
	echo "# Remake mx3_x4.gds"
na2_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/na2_x1.ap
	echo "# Remake na2_x1.gds"
na2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/na2_x4.ap
	echo "# Remake na2_x4.gds"
na3_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/na3_x1.ap
	echo "# Remake na3_x1.gds"
na3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/na3_x4.ap
	echo "# Remake na3_x4.gds"
na4_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/na4_x1.ap
	echo "# Remake na4_x1.gds"
na4_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/na4_x4.ap
	echo "# Remake na4_x4.gds"
nao22_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nao22_x1.ap
	echo "# Remake nao22_x1.gds"
nao22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/nao22_x4.ap
	echo "# Remake nao22_x4.gds"
nao2o22_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nao2o22_x1.ap
	echo "# Remake nao2o22_x1.gds"
nao2o22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/nao2o22_x4.ap
	echo "# Remake nao2o22_x4.gds"
nmx2_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nmx2_x1.ap
	echo "# Remake nmx2_x1.gds"
nmx2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/nmx2_x4.ap
	echo "# Remake nmx2_x4.gds"
nmx3_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nmx3_x1.ap
	echo "# Remake nmx3_x1.gds"
nmx3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/nmx3_x4.ap
	echo "# Remake nmx3_x4.gds"
no2_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/no2_x1.ap
	echo "# Remake no2_x1.gds"
no2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/no2_x4.ap
	echo "# Remake no2_x4.gds"
no3_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/no3_x1.ap
	echo "# Remake no3_x1.gds"
no3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/no3_x4.ap
	echo "# Remake no3_x4.gds"
no4_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/no4_x1.ap
	echo "# Remake no4_x1.gds"
no4_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/no4_x4.ap
	echo "# Remake no4_x4.gds"
noa22_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa22_x1.ap
	echo "# Remake noa22_x1.gds"
noa22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa22_x4.ap
	echo "# Remake noa22_x4.gds"
noa2a22_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a22_x1.ap
	echo "# Remake noa2a22_x1.gds"
noa2a22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a22_x4.ap
	echo "# Remake noa2a22_x4.gds"
noa2a2a23_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a2a23_x1.ap
	echo "# Remake noa2a2a23_x1.gds"
noa2a2a23_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a2a23_x4.ap
	echo "# Remake noa2a2a23_x4.gds"
noa2a2a2a24_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a2a2a24_x1.ap
	echo "# Remake noa2a2a2a24_x1.gds"
noa2a2a2a24_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2a2a2a24_x4.ap
	echo "# Remake noa2a2a2a24_x4.gds"
noa2ao222_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2ao222_x1.ap
	echo "# Remake noa2ao222_x1.gds"
noa2ao222_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa2ao222_x4.ap
	echo "# Remake noa2ao222_x4.gds"
noa3ao322_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa3ao322_x1.ap
	echo "# Remake noa3ao322_x1.gds"
noa3ao322_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/noa3ao322_x4.ap
	echo "# Remake noa3ao322_x4.gds"
nts_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nts_x1.ap
	echo "# Remake nts_x1.gds"
nts_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/nts_x2.ap
	echo "# Remake nts_x2.gds"
nxr2_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/nxr2_x1.ap
	echo "# Remake nxr2_x1.gds"
nxr2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/nxr2_x4.ap
	echo "# Remake nxr2_x4.gds"
o2_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/o2_x2.ap
	echo "# Remake o2_x2.gds"
o2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/o2_x4.ap
	echo "# Remake o2_x4.gds"
o3_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/o3_x2.ap
	echo "# Remake o3_x2.gds"
o3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/o3_x4.ap
	echo "# Remake o3_x4.gds"
o4_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/o4_x2.ap
	echo "# Remake o4_x2.gds"
o4_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/o4_x4.ap
	echo "# Remake o4_x4.gds"
oa22_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa22_x2.ap
	echo "# Remake oa22_x2.gds"
oa22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa22_x4.ap
	echo "# Remake oa22_x4.gds"
oa2a22_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a22_x2.ap
	echo "# Remake oa2a22_x2.gds"
oa2a22_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a22_x4.ap
	echo "# Remake oa2a22_x4.gds"
oa2a2a23_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a2a23_x2.ap
	echo "# Remake oa2a2a23_x2.gds"
oa2a2a23_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a2a23_x4.ap
	echo "# Remake oa2a2a23_x4.gds"
oa2a2a2a24_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a2a2a24_x2.ap
	echo "# Remake oa2a2a2a24_x2.gds"
oa2a2a2a24_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2a2a2a24_x4.ap
	echo "# Remake oa2a2a2a24_x4.gds"
oa2ao222_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2ao222_x2.ap
	echo "# Remake oa2ao222_x2.gds"
oa2ao222_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa2ao222_x4.ap
	echo "# Remake oa2ao222_x4.gds"
oa3ao322_x2.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa3ao322_x2.ap
	echo "# Remake oa3ao322_x2.gds"
oa3ao322_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/oa3ao322_x4.ap
	echo "# Remake oa3ao322_x4.gds"
on12_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/on12_x1.ap
	echo "# Remake on12_x1.gds"
on12_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/on12_x4.ap
	echo "# Remake on12_x4.gds"
one_x0.gds: /usr/share/pharosc/alliance/cells/ssxlib/one_x0.ap
	echo "# Remake one_x0.gds"
powmid_x0.gds: /usr/share/pharosc/alliance/cells/ssxlib/powmid_x0.ap
	echo "# Remake powmid_x0.gds"
rowend_x0.gds: /usr/share/pharosc/alliance/cells/ssxlib/rowend_x0.ap
	echo "# Remake rowend_x0.gds"
sff1_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/sff1_x4.ap
	echo "# Remake sff1_x4.gds"
sff2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/sff2_x4.ap
	echo "# Remake sff2_x4.gds"
sff3_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/sff3_x4.ap
	echo "# Remake sff3_x4.gds"
tie_x0.gds: /usr/share/pharosc/alliance/cells/ssxlib/tie_x0.ap
	echo "# Remake tie_x0.gds"
ts_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/ts_x4.ap
	echo "# Remake ts_x4.gds"
ts_x8.gds: /usr/share/pharosc/alliance/cells/ssxlib/ts_x8.ap
	echo "# Remake ts_x8.gds"
xr2_x1.gds: /usr/share/pharosc/alliance/cells/ssxlib/xr2_x1.ap
	echo "# Remake xr2_x1.gds"
xr2_x4.gds: /usr/share/pharosc/alliance/cells/ssxlib/xr2_x4.ap
	echo "# Remake xr2_x4.gds"
zero_x0.gds: /usr/share/pharosc/alliance/cells/ssxlib/zero_x0.ap
	echo "# Remake zero_x0.gds"
