
SHELL=/bin/bash

an2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x05.ap
	echo "# Remake an2v0x05.gds"
an2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x1.ap
	echo "# Remake an2v0x1.gds"
an2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x2.ap
	echo "# Remake an2v0x2.gds"
an2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x3.ap
	echo "# Remake an2v0x3.gds"
an2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x4.ap
	echo "# Remake an2v0x4.gds"
an2v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x6.ap
	echo "# Remake an2v0x6.gds"
an2v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v0x8.ap
	echo "# Remake an2v0x8.gds"
an2v2x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v2x2.ap
	echo "# Remake an2v2x2.gds"
an2v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v4x1.ap
	echo "# Remake an2v4x1.gds"
an2v4x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v4x2.ap
	echo "# Remake an2v4x2.gds"
an2v4x4.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v4x4.ap
	echo "# Remake an2v4x4.gds"
an2v4x8.gds: /usr/share/pharosc/alliance/cells/vsclib/an2v4x8.ap
	echo "# Remake an2v4x8.gds"
an3v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v0x05.ap
	echo "# Remake an3v0x05.gds"
an3v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v0x1.ap
	echo "# Remake an3v0x1.gds"
an3v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v0x2.ap
	echo "# Remake an3v0x2.gds"
an3v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v0x4.ap
	echo "# Remake an3v0x4.gds"
an3v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v4x1.ap
	echo "# Remake an3v4x1.gds"
an3v4x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v4x2.ap
	echo "# Remake an3v4x2.gds"
an3v6x05.gds: /usr/share/pharosc/alliance/cells/vsclib/an3v6x05.ap
	echo "# Remake an3v6x05.gds"
an4v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/an4v0x05.ap
	echo "# Remake an4v0x05.gds"
an4v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an4v0x1.ap
	echo "# Remake an4v0x1.gds"
an4v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/an4v0x2.ap
	echo "# Remake an4v0x2.gds"
an4v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/an4v0x4.ap
	echo "# Remake an4v0x4.gds"
an4v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/an4v4x1.ap
	echo "# Remake an4v4x1.gds"
aoi112v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi112v0x05.ap
	echo "# Remake aoi112v0x05.gds"
aoi211v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x05.ap
	echo "# Remake aoi211v0x05.gds"
aoi211v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x1.ap
	echo "# Remake aoi211v0x1.gds"
aoi211v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi211v0x2.ap
	echo "# Remake aoi211v0x2.gds"
aoi211v5x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi211v5x05.ap
	echo "# Remake aoi211v5x05.gds"
aoi21a2bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2bv0x05.ap
	echo "# Remake aoi21a2bv0x05.gds"
aoi21a2bv5x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2bv5x05.ap
	echo "# Remake aoi21a2bv5x05.gds"
aoi21a2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21a2v0x05.ap
	echo "# Remake aoi21a2v0x05.gds"
aoi21bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21bv0x05.ap
	echo "# Remake aoi21bv0x05.gds"
aoi21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x05.ap
	echo "# Remake aoi21v0x05.gds"
aoi21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x1.ap
	echo "# Remake aoi21v0x1.gds"
aoi21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi21v0x2.ap
	echo "# Remake aoi21v0x2.gds"
aoi22v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x05.ap
	echo "# Remake aoi22v0x05.gds"
aoi22v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x1.ap
	echo "# Remake aoi22v0x1.gds"
aoi22v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x2.ap
	echo "# Remake aoi22v0x2.gds"
aoi22v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x3.ap
	echo "# Remake aoi22v0x3.gds"
aoi22v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v0x4.ap
	echo "# Remake aoi22v0x4.gds"
aoi22v5x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi22v5x05.ap
	echo "# Remake aoi22v5x05.gds"
aoi31v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x05.ap
	echo "# Remake aoi31v0x05.gds"
aoi31v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x1.ap
	echo "# Remake aoi31v0x1.gds"
aoi31v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x2.ap
	echo "# Remake aoi31v0x2.gds"
aoi31v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/aoi31v0x3.ap
	echo "# Remake aoi31v0x3.gds"
aon21bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x05.ap
	echo "# Remake aon21bv0x05.gds"
aon21bv0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x1.ap
	echo "# Remake aon21bv0x1.gds"
aon21bv0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x2.ap
	echo "# Remake aon21bv0x2.gds"
aon21bv0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x3.ap
	echo "# Remake aon21bv0x3.gds"
aon21bv0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21bv0x4.ap
	echo "# Remake aon21bv0x4.gds"
aon21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/aon21v0x05.ap
	echo "# Remake aon21v0x05.gds"
bf1v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x05.ap
	echo "# Remake bf1v0x05.gds"
bf1v0x12.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x12.ap
	echo "# Remake bf1v0x12.gds"
bf1v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x1.ap
	echo "# Remake bf1v0x1.gds"
bf1v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x2.ap
	echo "# Remake bf1v0x2.gds"
bf1v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x3.ap
	echo "# Remake bf1v0x3.gds"
bf1v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x4.ap
	echo "# Remake bf1v0x4.gds"
bf1v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x6.ap
	echo "# Remake bf1v0x6.gds"
bf1v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v0x8.ap
	echo "# Remake bf1v0x8.gds"
bf1v1x2.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v1x2.ap
	echo "# Remake bf1v1x2.gds"
bf1v2x1.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x1.ap
	echo "# Remake bf1v2x1.gds"
bf1v2x2.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x2.ap
	echo "# Remake bf1v2x2.gds"
bf1v2x3.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x3.ap
	echo "# Remake bf1v2x3.gds"
bf1v2x4.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x4.ap
	echo "# Remake bf1v2x4.gds"
bf1v2x6.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x6.ap
	echo "# Remake bf1v2x6.gds"
bf1v2x8.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v2x8.ap
	echo "# Remake bf1v2x8.gds"
bf1v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v4x1.ap
	echo "# Remake bf1v4x1.gds"
bf1v5x05.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x05.ap
	echo "# Remake bf1v5x05.gds"
bf1v5x1.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x1.ap
	echo "# Remake bf1v5x1.gds"
bf1v5x2.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x2.ap
	echo "# Remake bf1v5x2.gds"
bf1v5x4.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v5x4.ap
	echo "# Remake bf1v5x4.gds"
bf1v6x2.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v6x2.ap
	echo "# Remake bf1v6x2.gds"
bf1v8x4.gds: /usr/share/pharosc/alliance/cells/vsclib/bf1v8x4.ap
	echo "# Remake bf1v8x4.gds"
bsi2v2x1.gds: /usr/share/pharosc/alliance/cells/vsclib/bsi2v2x1.ap
	echo "# Remake bsi2v2x1.gds"
cgi2abv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x05.ap
	echo "# Remake cgi2abv0x05.gds"
cgi2abv0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x1.ap
	echo "# Remake cgi2abv0x1.gds"
cgi2abv0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2abv0x2.ap
	echo "# Remake cgi2abv0x2.gds"
cgi2bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x05.ap
	echo "# Remake cgi2bv0x05.gds"
cgi2bv0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x1.ap
	echo "# Remake cgi2bv0x1.gds"
cgi2bv0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x2.ap
	echo "# Remake cgi2bv0x2.gds"
cgi2bv0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2bv0x3.ap
	echo "# Remake cgi2bv0x3.gds"
cgi2cv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x05.ap
	echo "# Remake cgi2cv0x05.gds"
cgi2cv0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x1.ap
	echo "# Remake cgi2cv0x1.gds"
cgi2cv0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x2.ap
	echo "# Remake cgi2cv0x2.gds"
cgi2cv0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2cv0x3.ap
	echo "# Remake cgi2cv0x3.gds"
cgi2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x05.ap
	echo "# Remake cgi2v0x05.gds"
cgi2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x1.ap
	echo "# Remake cgi2v0x1.gds"
cgi2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x2.ap
	echo "# Remake cgi2v0x2.gds"
cgi2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/cgi2v0x3.ap
	echo "# Remake cgi2v0x3.gds"
dfnt1v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/dfnt1v0x2.ap
	echo "# Remake dfnt1v0x2.gds"
dly1v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/dly1v0x05.ap
	echo "# Remake dly1v0x05.gds"
dly2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/dly2v0x05.ap
	echo "# Remake dly2v0x05.gds"
dly2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/dly2v0x1.ap
	echo "# Remake dly2v0x1.gds"
ha2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/ha2v0x2.ap
	echo "# Remake ha2v0x2.gds"
iv1v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x05.ap
	echo "# Remake iv1v0x05.gds"
iv1v0x12.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x12.ap
	echo "# Remake iv1v0x12.gds"
iv1v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x1.ap
	echo "# Remake iv1v0x1.gds"
iv1v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x2.ap
	echo "# Remake iv1v0x2.gds"
iv1v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x3.ap
	echo "# Remake iv1v0x3.gds"
iv1v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x4.ap
	echo "# Remake iv1v0x4.gds"
iv1v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x6.ap
	echo "# Remake iv1v0x6.gds"
iv1v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v0x8.ap
	echo "# Remake iv1v0x8.gds"
iv1v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x05.ap
	echo "# Remake iv1v1x05.gds"
iv1v1x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x1.ap
	echo "# Remake iv1v1x1.gds"
iv1v1x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x2.ap
	echo "# Remake iv1v1x2.gds"
iv1v1x4.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x4.ap
	echo "# Remake iv1v1x4.gds"
iv1v1x8.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v1x8.ap
	echo "# Remake iv1v1x8.gds"
iv1v2x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v2x2.ap
	echo "# Remake iv1v2x2.gds"
iv1v3x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x1.ap
	echo "# Remake iv1v3x1.gds"
iv1v3x3.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x3.ap
	echo "# Remake iv1v3x3.gds"
iv1v3x6.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v3x6.ap
	echo "# Remake iv1v3x6.gds"
iv1v4x12.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x12.ap
	echo "# Remake iv1v4x12.gds"
iv1v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x1.ap
	echo "# Remake iv1v4x1.gds"
iv1v4x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x2.ap
	echo "# Remake iv1v4x2.gds"
iv1v4x3.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x3.ap
	echo "# Remake iv1v4x3.gds"
iv1v4x4.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x4.ap
	echo "# Remake iv1v4x4.gds"
iv1v4x6.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x6.ap
	echo "# Remake iv1v4x6.gds"
iv1v4x8.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v4x8.ap
	echo "# Remake iv1v4x8.gds"
iv1v5x12.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x12.ap
	echo "# Remake iv1v5x12.gds"
iv1v5x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x1.ap
	echo "# Remake iv1v5x1.gds"
iv1v5x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x2.ap
	echo "# Remake iv1v5x2.gds"
iv1v5x3.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x3.ap
	echo "# Remake iv1v5x3.gds"
iv1v5x4.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x4.ap
	echo "# Remake iv1v5x4.gds"
iv1v5x6.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x6.ap
	echo "# Remake iv1v5x6.gds"
iv1v5x8.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v5x8.ap
	echo "# Remake iv1v5x8.gds"
iv1v6x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v6x1.ap
	echo "# Remake iv1v6x1.gds"
iv1v6x2.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v6x2.ap
	echo "# Remake iv1v6x2.gds"
iv1v7x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v7x1.ap
	echo "# Remake iv1v7x1.gds"
iv1v8x1.gds: /usr/share/pharosc/alliance/cells/vsclib/iv1v8x1.ap
	echo "# Remake iv1v8x1.gds"
mxi2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x05.ap
	echo "# Remake mxi2v0x05.gds"
mxi2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x1.ap
	echo "# Remake mxi2v0x1.gds"
mxi2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v0x2.ap
	echo "# Remake mxi2v0x2.gds"
mxi2v2x05.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x05.ap
	echo "# Remake mxi2v2x05.gds"
mxi2v2x1.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x1.ap
	echo "# Remake mxi2v2x1.gds"
mxi2v2x2.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x2.ap
	echo "# Remake mxi2v2x2.gds"
mxi2v2x3.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x3.ap
	echo "# Remake mxi2v2x3.gds"
mxi2v2x4.gds: /usr/share/pharosc/alliance/cells/vsclib/mxi2v2x4.ap
	echo "# Remake mxi2v2x4.gds"
mxn2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/mxn2v0x05.ap
	echo "# Remake mxn2v0x05.gds"
mxn2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/mxn2v0x1.ap
	echo "# Remake mxn2v0x1.gds"
mxn2v2x1.gds: /usr/share/pharosc/alliance/cells/vsclib/mxn2v2x1.ap
	echo "# Remake mxn2v2x1.gds"
nd2abv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x05.ap
	echo "# Remake nd2abv0x05.gds"
nd2abv0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x1.ap
	echo "# Remake nd2abv0x1.gds"
nd2abv0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x2.ap
	echo "# Remake nd2abv0x2.gds"
nd2abv0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x3.ap
	echo "# Remake nd2abv0x3.gds"
nd2abv0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2abv0x4.ap
	echo "# Remake nd2abv0x4.gds"
nd2av0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x05.ap
	echo "# Remake nd2av0x05.gds"
nd2av0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x1.ap
	echo "# Remake nd2av0x1.gds"
nd2av0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x2.ap
	echo "# Remake nd2av0x2.gds"
nd2av0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x3.ap
	echo "# Remake nd2av0x3.gds"
nd2av0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x4.ap
	echo "# Remake nd2av0x4.gds"
nd2av0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x6.ap
	echo "# Remake nd2av0x6.gds"
nd2av0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2av0x8.ap
	echo "# Remake nd2av0x8.gds"
nd2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x05.ap
	echo "# Remake nd2v0x05.gds"
nd2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x1.ap
	echo "# Remake nd2v0x1.gds"
nd2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x2.ap
	echo "# Remake nd2v0x2.gds"
nd2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x3.ap
	echo "# Remake nd2v0x3.gds"
nd2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x4.ap
	echo "# Remake nd2v0x4.gds"
nd2v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x6.ap
	echo "# Remake nd2v0x6.gds"
nd2v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v0x8.ap
	echo "# Remake nd2v0x8.gds"
nd2v3x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x05.ap
	echo "# Remake nd2v3x05.gds"
nd2v3x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x1.ap
	echo "# Remake nd2v3x1.gds"
nd2v3x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x2.ap
	echo "# Remake nd2v3x2.gds"
nd2v3x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x3.ap
	echo "# Remake nd2v3x3.gds"
nd2v3x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v3x4.ap
	echo "# Remake nd2v3x4.gds"
nd2v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x1.ap
	echo "# Remake nd2v4x1.gds"
nd2v4x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x2.ap
	echo "# Remake nd2v4x2.gds"
nd2v4x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x3.ap
	echo "# Remake nd2v4x3.gds"
nd2v4x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x4.ap
	echo "# Remake nd2v4x4.gds"
nd2v4x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x6.ap
	echo "# Remake nd2v4x6.gds"
nd2v4x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v4x8.ap
	echo "# Remake nd2v4x8.gds"
nd2v5x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x05.ap
	echo "# Remake nd2v5x05.gds"
nd2v5x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x1.ap
	echo "# Remake nd2v5x1.gds"
nd2v5x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x2.ap
	echo "# Remake nd2v5x2.gds"
nd2v5x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x3.ap
	echo "# Remake nd2v5x3.gds"
nd2v5x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x4.ap
	echo "# Remake nd2v5x4.gds"
nd2v5x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x6.ap
	echo "# Remake nd2v5x6.gds"
nd2v5x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v5x8.ap
	echo "# Remake nd2v5x8.gds"
nd2v6x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd2v6x3.ap
	echo "# Remake nd2v6x3.gds"
nd3abv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3abv0x05.ap
	echo "# Remake nd3abv0x05.gds"
nd3av0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3av0x05.ap
	echo "# Remake nd3av0x05.gds"
nd3v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x05.ap
	echo "# Remake nd3v0x05.gds"
nd3v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x1.ap
	echo "# Remake nd3v0x1.gds"
nd3v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x2.ap
	echo "# Remake nd3v0x2.gds"
nd3v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x3.ap
	echo "# Remake nd3v0x3.gds"
nd3v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x4.ap
	echo "# Remake nd3v0x4.gds"
nd3v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v0x6.ap
	echo "# Remake nd3v0x6.gds"
nd3v5x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x2.ap
	echo "# Remake nd3v5x2.gds"
nd3v5x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x3.ap
	echo "# Remake nd3v5x3.gds"
nd3v5x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x4.ap
	echo "# Remake nd3v5x4.gds"
nd3v5x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v5x6.ap
	echo "# Remake nd3v5x6.gds"
nd3v6x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nd3v6x6.ap
	echo "# Remake nd3v6x6.gds"
nd4v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x05.ap
	echo "# Remake nd4v0x05.gds"
nd4v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x1.ap
	echo "# Remake nd4v0x1.gds"
nd4v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x2.ap
	echo "# Remake nd4v0x2.gds"
nd4v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nd4v0x3.ap
	echo "# Remake nd4v0x3.gds"
nr2av0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x1.ap
	echo "# Remake nr2av0x1.gds"
nr2av0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x2.ap
	echo "# Remake nr2av0x2.gds"
nr2av0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x3.ap
	echo "# Remake nr2av0x3.gds"
nr2av0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x4.ap
	echo "# Remake nr2av0x4.gds"
nr2av0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av0x6.ap
	echo "# Remake nr2av0x6.gds"
nr2av1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2av1x05.ap
	echo "# Remake nr2av1x05.gds"
nr2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x05.ap
	echo "# Remake nr2v0x05.gds"
nr2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x1.ap
	echo "# Remake nr2v0x1.gds"
nr2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x2.ap
	echo "# Remake nr2v0x2.gds"
nr2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x3.ap
	echo "# Remake nr2v0x3.gds"
nr2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x4.ap
	echo "# Remake nr2v0x4.gds"
nr2v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x6.ap
	echo "# Remake nr2v0x6.gds"
nr2v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v0x8.ap
	echo "# Remake nr2v0x8.gds"
nr2v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x05.ap
	echo "# Remake nr2v1x05.gds"
nr2v1x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x1.ap
	echo "# Remake nr2v1x1.gds"
nr2v1x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x2.ap
	echo "# Remake nr2v1x2.gds"
nr2v1x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x3.ap
	echo "# Remake nr2v1x3.gds"
nr2v1x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x4.ap
	echo "# Remake nr2v1x4.gds"
nr2v1x6.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x6.ap
	echo "# Remake nr2v1x6.gds"
nr2v1x8.gds: /usr/share/pharosc/alliance/cells/vsclib/nr2v1x8.ap
	echo "# Remake nr2v1x8.gds"
nr3abv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3abv0x05.ap
	echo "# Remake nr3abv0x05.gds"
nr3av0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3av0x05.ap
	echo "# Remake nr3av0x05.gds"
nr3v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x05.ap
	echo "# Remake nr3v0x05.gds"
nr3v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x1.ap
	echo "# Remake nr3v0x1.gds"
nr3v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x2.ap
	echo "# Remake nr3v0x2.gds"
nr3v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x3.ap
	echo "# Remake nr3v0x3.gds"
nr3v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v0x4.ap
	echo "# Remake nr3v0x4.gds"
nr3v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr3v1x05.ap
	echo "# Remake nr3v1x05.gds"
nr4v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/nr4v0x1.ap
	echo "# Remake nr4v0x1.gds"
nr4v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/nr4v0x2.ap
	echo "# Remake nr4v0x2.gds"
nr4v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/nr4v1x05.ap
	echo "# Remake nr4v1x05.gds"
oai211v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai211v0x05.ap
	echo "# Remake oai211v0x05.gds"
oai211v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/oai211v0x1.ap
	echo "# Remake oai211v0x1.gds"
oai21a2bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21a2bv0x05.ap
	echo "# Remake oai21a2bv0x05.gds"
oai21a2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21a2v0x05.ap
	echo "# Remake oai21a2v0x05.gds"
oai21a2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21a2v0x1.ap
	echo "# Remake oai21a2v0x1.gds"
oai21bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21bv0x05.ap
	echo "# Remake oai21bv0x05.gds"
oai21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x05.ap
	echo "# Remake oai21v0x05.gds"
oai21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x1.ap
	echo "# Remake oai21v0x1.gds"
oai21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x2.ap
	echo "# Remake oai21v0x2.gds"
oai21v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x3.ap
	echo "# Remake oai21v0x3.gds"
oai21v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x4.ap
	echo "# Remake oai21v0x4.gds"
oai21v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x6.ap
	echo "# Remake oai21v0x6.gds"
oai21v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/oai21v0x8.ap
	echo "# Remake oai21v0x8.gds"
oai22v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x05.ap
	echo "# Remake oai22v0x05.gds"
oai22v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x1.ap
	echo "# Remake oai22v0x1.gds"
oai22v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/oai22v0x2.ap
	echo "# Remake oai22v0x2.gds"
oai23av0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai23av0x05.ap
	echo "# Remake oai23av0x05.gds"
oai31v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x05.ap
	echo "# Remake oai31v0x05.gds"
oai31v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x1.ap
	echo "# Remake oai31v0x1.gds"
oai31v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/oai31v0x2.ap
	echo "# Remake oai31v0x2.gds"
oan21bv0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oan21bv0x05.ap
	echo "# Remake oan21bv0x05.gds"
oan21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/oan21v0x05.ap
	echo "# Remake oan21v0x05.gds"
or2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x05.ap
	echo "# Remake or2v0x05.gds"
or2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x1.ap
	echo "# Remake or2v0x1.gds"
or2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x2.ap
	echo "# Remake or2v0x2.gds"
or2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x3.ap
	echo "# Remake or2v0x3.gds"
or2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x4.ap
	echo "# Remake or2v0x4.gds"
or2v0x8.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v0x8.ap
	echo "# Remake or2v0x8.gds"
or2v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v4x1.ap
	echo "# Remake or2v4x1.gds"
or2v7x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or2v7x2.ap
	echo "# Remake or2v7x2.gds"
or3v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v0x05.ap
	echo "# Remake or3v0x05.gds"
or3v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v0x1.ap
	echo "# Remake or3v0x1.gds"
or3v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v0x2.ap
	echo "# Remake or3v0x2.gds"
or3v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v0x3.ap
	echo "# Remake or3v0x3.gds"
or3v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v0x4.ap
	echo "# Remake or3v0x4.gds"
or3v3x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v3x2.ap
	echo "# Remake or3v3x2.gds"
or3v4x05.gds: /usr/share/pharosc/alliance/cells/vsclib/or3v4x05.ap
	echo "# Remake or3v4x05.gds"
or4v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v0x05.ap
	echo "# Remake or4v0x05.gds"
or4v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v0x1.ap
	echo "# Remake or4v0x1.gds"
or4v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v0x2.ap
	echo "# Remake or4v0x2.gds"
or4v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v0x3.ap
	echo "# Remake or4v0x3.gds"
or4v3x2.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v3x2.ap
	echo "# Remake or4v3x2.gds"
or4v4x05.gds: /usr/share/pharosc/alliance/cells/vsclib/or4v4x05.ap
	echo "# Remake or4v4x05.gds"
rowend_x0.gds: /usr/share/pharosc/alliance/cells/vsclib/rowend_x0.ap
	echo "# Remake rowend_x0.gds"
tie_x0.gds: /usr/share/pharosc/alliance/cells/vsclib/tie_x0.ap
	echo "# Remake tie_x0.gds"
vddtie.gds: /usr/share/pharosc/alliance/cells/vsclib/vddtie.ap
	echo "# Remake vddtie.gds"
vfeed1.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed1.ap
	echo "# Remake vfeed1.gds"
vfeed2.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed2.ap
	echo "# Remake vfeed2.gds"
vfeed3.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed3.ap
	echo "# Remake vfeed3.gds"
vfeed4.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed4.ap
	echo "# Remake vfeed4.gds"
vfeed5.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed5.ap
	echo "# Remake vfeed5.gds"
vfeed6.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed6.ap
	echo "# Remake vfeed6.gds"
vfeed7.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed7.ap
	echo "# Remake vfeed7.gds"
vfeed8.gds: /usr/share/pharosc/alliance/cells/vsclib/vfeed8.ap
	echo "# Remake vfeed8.gds"
vsstie.gds: /usr/share/pharosc/alliance/cells/vsclib/vsstie.ap
	echo "# Remake vsstie.gds"
xaoi21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x05.ap
	echo "# Remake xaoi21v0x05.gds"
xaoi21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x1.ap
	echo "# Remake xaoi21v0x1.gds"
xaoi21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xaoi21v0x2.ap
	echo "# Remake xaoi21v0x2.gds"
xaon21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x05.ap
	echo "# Remake xaon21v0x05.gds"
xaon21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x1.ap
	echo "# Remake xaon21v0x1.gds"
xaon21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x2.ap
	echo "# Remake xaon21v0x2.gds"
xaon21v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/xaon21v0x3.ap
	echo "# Remake xaon21v0x3.gds"
xnai21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnai21v0x05.ap
	echo "# Remake xnai21v0x05.gds"
xnai21v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnai21v1x05.ap
	echo "# Remake xnai21v1x05.gds"
xnai21v2x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnai21v2x05.ap
	echo "# Remake xnai21v2x05.gds"
xnr2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x05.ap
	echo "# Remake xnr2v0x05.gds"
xnr2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x1.ap
	echo "# Remake xnr2v0x1.gds"
xnr2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x2.ap
	echo "# Remake xnr2v0x2.gds"
xnr2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x3.ap
	echo "# Remake xnr2v0x3.gds"
xnr2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v0x4.ap
	echo "# Remake xnr2v0x4.gds"
xnr2v6x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v6x1.ap
	echo "# Remake xnr2v6x1.gds"
xnr2v8x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr2v8x05.ap
	echo "# Remake xnr2v8x05.gds"
xnr3v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x05.ap
	echo "# Remake xnr3v1x05.gds"
xnr3v1x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x1.ap
	echo "# Remake xnr3v1x1.gds"
xnr3v1x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xnr3v1x2.ap
	echo "# Remake xnr3v1x2.gds"
xooi21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x05.ap
	echo "# Remake xooi21v0x05.gds"
xooi21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x1.ap
	echo "# Remake xooi21v0x1.gds"
xooi21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xooi21v0x2.ap
	echo "# Remake xooi21v0x2.gds"
xoon21v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x05.ap
	echo "# Remake xoon21v0x05.gds"
xoon21v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x1.ap
	echo "# Remake xoon21v0x1.gds"
xoon21v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x2.ap
	echo "# Remake xoon21v0x2.gds"
xoon21v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/xoon21v0x3.ap
	echo "# Remake xoon21v0x3.gds"
xor2v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x05.ap
	echo "# Remake xor2v0x05.gds"
xor2v0x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x1.ap
	echo "# Remake xor2v0x1.gds"
xor2v0x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x2.ap
	echo "# Remake xor2v0x2.gds"
xor2v0x3.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x3.ap
	echo "# Remake xor2v0x3.gds"
xor2v0x4.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x4.ap
	echo "# Remake xor2v0x4.gds"
xor2v0x6.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v0x6.ap
	echo "# Remake xor2v0x6.gds"
xor2v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v1x05.ap
	echo "# Remake xor2v1x05.gds"
xor2v1x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v1x1.ap
	echo "# Remake xor2v1x1.gds"
xor2v2x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x05.ap
	echo "# Remake xor2v2x05.gds"
xor2v2x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x1.ap
	echo "# Remake xor2v2x1.gds"
xor2v2x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v2x2.ap
	echo "# Remake xor2v2x2.gds"
xor2v3x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v3x1.ap
	echo "# Remake xor2v3x1.gds"
xor2v4x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v4x1.ap
	echo "# Remake xor2v4x1.gds"
xor2v5x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v5x1.ap
	echo "# Remake xor2v5x1.gds"
xor2v6x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v6x1.ap
	echo "# Remake xor2v6x1.gds"
xor2v7x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v7x1.ap
	echo "# Remake xor2v7x1.gds"
xor2v8x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x05.ap
	echo "# Remake xor2v8x05.gds"
xor2v8x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x1.ap
	echo "# Remake xor2v8x1.gds"
xor2v8x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xor2v8x2.ap
	echo "# Remake xor2v8x2.gds"
xor3v0x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor3v0x05.ap
	echo "# Remake xor3v0x05.gds"
xor3v1x05.gds: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x05.ap
	echo "# Remake xor3v1x05.gds"
xor3v1x1.gds: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x1.ap
	echo "# Remake xor3v1x1.gds"
xor3v1x2.gds: /usr/share/pharosc/alliance/cells/vsclib/xor3v1x2.ap
	echo "# Remake xor3v1x2.gds"
